apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adaptationservice.name }}
  namespace: {{.Values.adaptationservice.namespace}}
spec:
  replicas: {{ .Values.adaptationservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.adaptationservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adaptationservice.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.adaptationname  }}
      containers:
      - name: adaptation-service
        image: {{ .Values.imagestore.adaptationservice.registry}}{{ .Values.imagestore.adaptationservice.repository }}:{{ .Values.imagestore.adaptationservice.tag }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMQP_URL
          value: {{ .Values.adaptationservice.amqpurl }}
        - name: INPUT_MOUNT
          value: {{ .Values.volumemountpath.source }}
        - name: OUTPUT_MOUNT
          value: {{ .Values.volumemountpath.target }}
        - name: REQUEST_PROCESSING_IMAGE
          value: {{ .Values.imagestore.requestprocessing.registry}}{{ .Values.imagestore.requestprocessing.repository }}:{{ .Values.imagestore.requestprocessing.tag }}
        - name: REQUEST_PROCESSING_TIMEOUT
          value: {{ .Values.icapserviceconfig.processingtimeoutduration }}
        {{- if .Values.queue.messagebrokersecret }}
        - name: MESSAGE_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.queue.messagebrokersecret }}
              key: username
        - name: MESSAGE_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.queue.messagebrokersecret }}
              key: password
        {{- end }}          
        - name: ADAPTATION_REQUEST_QUEUE_HOSTNAME
          value: {{ .Values.queue.adaptationRequest.hostname }}
        - name: ADAPTATION_REQUEST_QUEUE_PORT
          value: {{ .Values.queue.adaptationRequest.port }}
        - name: ARCHIVE_ADAPTATION_QUEUE_REQUEST_HOSTNAME
          value: {{ .Values.queue.archiveadaptationrequest.hostname }}
        - name: ARCHIVE_ADAPTATION_REQUEST_QUEUE_PORT
          value: {{ .Values.queue.archiveadaptationrequest.port }}
        - name: TRANSACTION_EVENT_QUEUE_HOSTNAME
          value: {{ .Values.queue.transactionevent.hostname}}
        - name: TRANSACTION_EVENT_QUEUE_PORT
          value: {{ .Values.queue.transactionevent.port }}
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "0.5"
            memory: 100Mi
      imagePullSecrets:
        - name: adaptation-registry-credential
