apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.archiveadaptationname  }}
  namespace: {{.Values.adaptationservice.namespace}}
  labels:
    environment: {{ .Values.environment | default "development" | quote }}