kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.archiveadaptationservice.rolename }}
  namespace: {{.Values.adaptationservice.namespace}}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]