apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.eventsubmissionservice.name }}
  namespace: {{.Values.adaptationservice.namespace}}
spec:
  replicas: {{ .Values.eventsubmissionservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.eventsubmissionservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.eventsubmissionservice.name }}
    spec:
      containers:
      - name: event-submission-service
        image: {{ .Values.imagestore.eventsubmission.registry}}{{ .Values.imagestore.eventsubmission.repository }}:{{ .Values.imagestore.eventsubmission.tag }}
        env:
        - name: ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: transactionstoresecret
              key: accountName
        - name: ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: transactionstoresecret
              key: accountKey
        - name: TRANSACTION_EVENT_QUEUE_HOSTNAME
          value: {{ .Values.queue.transactionevent.hostname}}
        - name: TRANSACTION_EVENT_QUEUE_PORT
          value: {{ .Values.queue.transactionevent.port }}              
        {{- if .Values.queue.messagebrokersecret }}
        - name: MESSAGE_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.queue.messagebrokersecret }}
              key: username
        - name: MESSAGE_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.queue.messagebrokersecret }}
              key: password
        {{- end }}               
      imagePullSecrets:
        - name: adaptation-registry-credential

