apiVersion: v1
kind: Secret
metadata:
  name: policyupdateservicesecret
  namespace: {{.Values.adaptationservice.namespace}}
type: Opaque
data:
  username: {{ .Values.secrets.policyupdateservice.username }}
  password: {{ .Values.secrets.policyupdateservice.password }}
