apiVersion: v1
kind: Secret
metadata:
  name: transactionstoresecret
  namespace: {{.Values.adaptationservice.namespace}}
data:
  azurestorageaccountname: {{ .Values.secrets.transactionstore.accountName | b64enc}}
  azurestorageaccountkey: {{ .Values.secrets.transactionstore.accountKey | b64enc}}