{{- $root := . }}
{{- range $key, $value  := .Values.transactionqueryservice.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
data:
  {{- range $subKey, $subValue  := $value }}
  {{ $subKey }}: {{ $subValue| b64enc }}
  {{- end }}
---
{{- end }}
