apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-operator-registry-credential
  namespace: rabbitmq-system
data:
  .dockerconfigjson: {{ .Values.secrets.containerregistry.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson